name: build sun50iw6p1 linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Show System Info
        run: |
          uname -a
          sudo free -h
          sudo fdisk -l 
          sudo cat /proc/cpuinfo

      - name: Install Packages
        run: bash init.sh

      - name: Get Source
        run: |
          echo "download source"
          wget --no-check-certificate -q -t 20 -T 20 https://dl.linux-sunxi.org/H6/H6-lichee-v1.1.tar.gz
          echo "extract source"
          tar -zxf H6-lichee-v1.1.tar.gz
          echo "copy build config"
          cp sun50iw6p1_linux_config lichee/.buildconfig

      - name: Run Pack
        run: |
          cd lichee/
          echo "start pack"
          ./build.sh pack
      
      
