name: build sun50iw6p1 new linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show System Info
        run: |
          uname -a
          sudo free -h
          sudo fdisk -l 
          sudo cat /proc/cpuinfo

      - name: Install Packages
        run: bash init.sh

      - name: Get Source
        run: |
          echo "download source"
          wget --no-check-certificate -q -t 20 -T 20 https://files.pine64.org/SDK/PINE-H64/PINE%20H64B%20BSP%204.9%20lichee.tar.xz
          echo "extract source"
          xz -d "PINE H64B BSP 4.9 lichee.tar.xz"
          tar -zxf "PINE H64B BSP 4.9 lichee.tar"
          echo "copy build config"
          cp sun50iw6p1_linux_config lichee/.buildconfig
          
      - name: Run Build
        run: |
          cd lichee/
          echo "start build"
          ./build.sh

      - name: Run Pack
        run: |
          cd lichee/
          echo "start pack"
          ./build.sh pack
      
      
